//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34014
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMedico.localhostConsulta {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consulta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Consulta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NumeroProntuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.Paciente PacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.Medico MedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.Enfermeiro EnfermeiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.DadosVitais DadosVitaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.Diagnostico DiagnosticoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.Receita ReceitaField;
        
        private System.DateTime DataConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacoesField;
        
        private int SituacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroProntuario {
            get {
                return this.NumeroProntuarioField;
            }
            set {
                if ((this.NumeroProntuarioField.Equals(value) != true)) {
                    this.NumeroProntuarioField = value;
                    this.RaisePropertyChanged("NumeroProntuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IMedico.localhostConsulta.Paciente Paciente {
            get {
                return this.PacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteField, value) != true)) {
                    this.PacienteField = value;
                    this.RaisePropertyChanged("Paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public IMedico.localhostConsulta.Medico Medico {
            get {
                return this.MedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicoField, value) != true)) {
                    this.MedicoField = value;
                    this.RaisePropertyChanged("Medico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IMedico.localhostConsulta.Enfermeiro Enfermeiro {
            get {
                return this.EnfermeiroField;
            }
            set {
                if ((object.ReferenceEquals(this.EnfermeiroField, value) != true)) {
                    this.EnfermeiroField = value;
                    this.RaisePropertyChanged("Enfermeiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public IMedico.localhostConsulta.DadosVitais DadosVitais {
            get {
                return this.DadosVitaisField;
            }
            set {
                if ((object.ReferenceEquals(this.DadosVitaisField, value) != true)) {
                    this.DadosVitaisField = value;
                    this.RaisePropertyChanged("DadosVitais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public IMedico.localhostConsulta.Diagnostico Diagnostico {
            get {
                return this.DiagnosticoField;
            }
            set {
                if ((object.ReferenceEquals(this.DiagnosticoField, value) != true)) {
                    this.DiagnosticoField = value;
                    this.RaisePropertyChanged("Diagnostico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public IMedico.localhostConsulta.Receita Receita {
            get {
                return this.ReceitaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceitaField, value) != true)) {
                    this.ReceitaField = value;
                    this.RaisePropertyChanged("Receita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime DataConsulta {
            get {
                return this.DataConsultaField;
            }
            set {
                if ((this.DataConsultaField.Equals(value) != true)) {
                    this.DataConsultaField = value;
                    this.RaisePropertyChanged("DataConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Observacoes {
            get {
                return this.ObservacoesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacoesField, value) != true)) {
                    this.ObservacoesField = value;
                    this.RaisePropertyChanged("Observacoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int Situacao {
            get {
                return this.SituacaoField;
            }
            set {
                if ((this.SituacaoField.Equals(value) != true)) {
                    this.SituacaoField = value;
                    this.RaisePropertyChanged("Situacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paciente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Paciente : IMedico.localhostConsulta.Pessoa {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomePaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeMaeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsavelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomePai {
            get {
                return this.NomePaiField;
            }
            set {
                if ((object.ReferenceEquals(this.NomePaiField, value) != true)) {
                    this.NomePaiField = value;
                    this.RaisePropertyChanged("NomePai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NomeMae {
            get {
                return this.NomeMaeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeMaeField, value) != true)) {
                    this.NomeMaeField = value;
                    this.RaisePropertyChanged("NomeMae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Responsavel {
            get {
                return this.ResponsavelField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsavelField, value) != true)) {
                    this.ResponsavelField = value;
                    this.RaisePropertyChanged("Responsavel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Raca {
            get {
                return this.RacaField;
            }
            set {
                if ((object.ReferenceEquals(this.RacaField, value) != true)) {
                    this.RacaField = value;
                    this.RaisePropertyChanged("Raca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medico", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Medico : IMedico.localhostConsulta.Pessoa {
        
        private int CrmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspecializacaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Crm {
            get {
                return this.CrmField;
            }
            set {
                if ((this.CrmField.Equals(value) != true)) {
                    this.CrmField = value;
                    this.RaisePropertyChanged("Crm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Especializacao {
            get {
                return this.EspecializacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecializacaoField, value) != true)) {
                    this.EspecializacaoField = value;
                    this.RaisePropertyChanged("Especializacao");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enfermeiro", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Enfermeiro : IMedico.localhostConsulta.Pessoa {
        
        private int CorenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Coren {
            get {
                return this.CorenField;
            }
            set {
                if ((this.CorenField.Equals(value) != true)) {
                    this.CorenField = value;
                    this.RaisePropertyChanged("Coren");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DadosVitais", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DadosVitais : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PressaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PulsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemperaturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RespiracaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Pressao {
            get {
                return this.PressaoField;
            }
            set {
                if ((object.ReferenceEquals(this.PressaoField, value) != true)) {
                    this.PressaoField = value;
                    this.RaisePropertyChanged("Pressao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Pulso {
            get {
                return this.PulsoField;
            }
            set {
                if ((object.ReferenceEquals(this.PulsoField, value) != true)) {
                    this.PulsoField = value;
                    this.RaisePropertyChanged("Pulso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Temperatura {
            get {
                return this.TemperaturaField;
            }
            set {
                if ((object.ReferenceEquals(this.TemperaturaField, value) != true)) {
                    this.TemperaturaField = value;
                    this.RaisePropertyChanged("Temperatura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Respiracao {
            get {
                return this.RespiracaoField;
            }
            set {
                if ((object.ReferenceEquals(this.RespiracaoField, value) != true)) {
                    this.RespiracaoField = value;
                    this.RaisePropertyChanged("Respiracao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Diagnostico", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Diagnostico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private System.DateTime DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformacoesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Data {
            get {
                return this.DataField;
            }
            set {
                if ((this.DataField.Equals(value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Informacoes {
            get {
                return this.InformacoesField;
            }
            set {
                if ((object.ReferenceEquals(this.InformacoesField, value) != true)) {
                    this.InformacoesField = value;
                    this.RaisePropertyChanged("Informacoes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Receita", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Receita : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.Paciente PacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.Medico MedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.ReceitaMedicamento[] ListaMedicamentosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IMedico.localhostConsulta.Paciente Paciente {
            get {
                return this.PacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.PacienteField, value) != true)) {
                    this.PacienteField = value;
                    this.RaisePropertyChanged("Paciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public IMedico.localhostConsulta.Medico Medico {
            get {
                return this.MedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicoField, value) != true)) {
                    this.MedicoField = value;
                    this.RaisePropertyChanged("Medico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IMedico.localhostConsulta.ReceitaMedicamento[] ListaMedicamentos {
            get {
                return this.ListaMedicamentosField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaMedicamentosField, value) != true)) {
                    this.ListaMedicamentosField = value;
                    this.RaisePropertyChanged("ListaMedicamentos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pessoa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IMedico.localhostConsulta.Enfermeiro))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IMedico.localhostConsulta.Medico))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(IMedico.localhostConsulta.Paciente))]
    public partial class Pessoa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RgField;
        
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.Endereco EnderecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Rg {
            get {
                return this.RgField;
            }
            set {
                if ((object.ReferenceEquals(this.RgField, value) != true)) {
                    this.RgField = value;
                    this.RaisePropertyChanged("Rg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public IMedico.localhostConsulta.Endereco Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Endereco", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Endereco : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogradouroField;
        
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Logradouro {
            get {
                return this.LogradouroField;
            }
            set {
                if ((object.ReferenceEquals(this.LogradouroField, value) != true)) {
                    this.LogradouroField = value;
                    this.RaisePropertyChanged("Logradouro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Uf {
            get {
                return this.UfField;
            }
            set {
                if ((object.ReferenceEquals(this.UfField, value) != true)) {
                    this.UfField = value;
                    this.RaisePropertyChanged("Uf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Pais {
            get {
                return this.PaisField;
            }
            set {
                if ((object.ReferenceEquals(this.PaisField, value) != true)) {
                    this.PaisField = value;
                    this.RaisePropertyChanged("Pais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceitaMedicamento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ReceitaMedicamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.Medicamento MedicamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IMedico.localhostConsulta.Receita ReceitaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstrucoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DosagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TempoTratamentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IMedico.localhostConsulta.Medicamento Medicamento {
            get {
                return this.MedicamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicamentoField, value) != true)) {
                    this.MedicamentoField = value;
                    this.RaisePropertyChanged("Medicamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public IMedico.localhostConsulta.Receita Receita {
            get {
                return this.ReceitaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceitaField, value) != true)) {
                    this.ReceitaField = value;
                    this.RaisePropertyChanged("Receita");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Instrucoes {
            get {
                return this.InstrucoesField;
            }
            set {
                if ((object.ReferenceEquals(this.InstrucoesField, value) != true)) {
                    this.InstrucoesField = value;
                    this.RaisePropertyChanged("Instrucoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantidadeField, value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Dosagem {
            get {
                return this.DosagemField;
            }
            set {
                if ((object.ReferenceEquals(this.DosagemField, value) != true)) {
                    this.DosagemField = value;
                    this.RaisePropertyChanged("Dosagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TempoTratamento {
            get {
                return this.TempoTratamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.TempoTratamentoField, value) != true)) {
                    this.TempoTratamentoField = value;
                    this.RaisePropertyChanged("TempoTratamento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Medicamento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Medicamento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeGenericoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComposicaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraIndicacoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DosagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IndicacoesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FabricanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeGenerico {
            get {
                return this.NomeGenericoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeGenericoField, value) != true)) {
                    this.NomeGenericoField = value;
                    this.RaisePropertyChanged("NomeGenerico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NomeComercial {
            get {
                return this.NomeComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeComercialField, value) != true)) {
                    this.NomeComercialField = value;
                    this.RaisePropertyChanged("NomeComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Composicao {
            get {
                return this.ComposicaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComposicaoField, value) != true)) {
                    this.ComposicaoField = value;
                    this.RaisePropertyChanged("Composicao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ContraIndicacoes {
            get {
                return this.ContraIndicacoesField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraIndicacoesField, value) != true)) {
                    this.ContraIndicacoesField = value;
                    this.RaisePropertyChanged("ContraIndicacoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Dosagem {
            get {
                return this.DosagemField;
            }
            set {
                if ((object.ReferenceEquals(this.DosagemField, value) != true)) {
                    this.DosagemField = value;
                    this.RaisePropertyChanged("Dosagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Indicacoes {
            get {
                return this.IndicacoesField;
            }
            set {
                if ((object.ReferenceEquals(this.IndicacoesField, value) != true)) {
                    this.IndicacoesField = value;
                    this.RaisePropertyChanged("Indicacoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Fabricante {
            get {
                return this.FabricanteField;
            }
            set {
                if ((object.ReferenceEquals(this.FabricanteField, value) != true)) {
                    this.FabricanteField = value;
                    this.RaisePropertyChanged("Fabricante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhostConsulta.ServiceConsultaSoap")]
    public interface ServiceConsultaSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento c no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastrarConsulta", ReplyAction="*")]
        IMedico.localhostConsulta.CadastrarConsultaResponse CadastrarConsulta(IMedico.localhostConsulta.CadastrarConsultaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento listarConsultaResult no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarConsulta", ReplyAction="*")]
        IMedico.localhostConsulta.listarConsultaResponse listarConsulta(IMedico.localhostConsulta.listarConsultaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento c no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pacienteTriagem", ReplyAction="*")]
        IMedico.localhostConsulta.pacienteTriagemResponse pacienteTriagem(IMedico.localhostConsulta.pacienteTriagemRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento c no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setMedicoConsulta", ReplyAction="*")]
        IMedico.localhostConsulta.setMedicoConsultaResponse setMedicoConsulta(IMedico.localhostConsulta.setMedicoConsultaRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento c no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/finalizarConsulta", ReplyAction="*")]
        IMedico.localhostConsulta.finalizarConsultaResponse finalizarConsulta(IMedico.localhostConsulta.finalizarConsultaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastrarConsultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CadastrarConsulta", Namespace="http://tempuri.org/", Order=0)]
        public IMedico.localhostConsulta.CadastrarConsultaRequestBody Body;
        
        public CadastrarConsultaRequest() {
        }
        
        public CadastrarConsultaRequest(IMedico.localhostConsulta.CadastrarConsultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CadastrarConsultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IMedico.localhostConsulta.Consulta c;
        
        public CadastrarConsultaRequestBody() {
        }
        
        public CadastrarConsultaRequestBody(IMedico.localhostConsulta.Consulta c) {
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastrarConsultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CadastrarConsultaResponse", Namespace="http://tempuri.org/", Order=0)]
        public IMedico.localhostConsulta.CadastrarConsultaResponseBody Body;
        
        public CadastrarConsultaResponse() {
        }
        
        public CadastrarConsultaResponse(IMedico.localhostConsulta.CadastrarConsultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CadastrarConsultaResponseBody {
        
        public CadastrarConsultaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarConsultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarConsulta", Namespace="http://tempuri.org/", Order=0)]
        public IMedico.localhostConsulta.listarConsultaRequestBody Body;
        
        public listarConsultaRequest() {
        }
        
        public listarConsultaRequest(IMedico.localhostConsulta.listarConsultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarConsultaRequestBody {
        
        public listarConsultaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarConsultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarConsultaResponse", Namespace="http://tempuri.org/", Order=0)]
        public IMedico.localhostConsulta.listarConsultaResponseBody Body;
        
        public listarConsultaResponse() {
        }
        
        public listarConsultaResponse(IMedico.localhostConsulta.listarConsultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarConsultaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IMedico.localhostConsulta.Consulta[] listarConsultaResult;
        
        public listarConsultaResponseBody() {
        }
        
        public listarConsultaResponseBody(IMedico.localhostConsulta.Consulta[] listarConsultaResult) {
            this.listarConsultaResult = listarConsultaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pacienteTriagemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pacienteTriagem", Namespace="http://tempuri.org/", Order=0)]
        public IMedico.localhostConsulta.pacienteTriagemRequestBody Body;
        
        public pacienteTriagemRequest() {
        }
        
        public pacienteTriagemRequest(IMedico.localhostConsulta.pacienteTriagemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pacienteTriagemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IMedico.localhostConsulta.Consulta c;
        
        public pacienteTriagemRequestBody() {
        }
        
        public pacienteTriagemRequestBody(IMedico.localhostConsulta.Consulta c) {
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pacienteTriagemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pacienteTriagemResponse", Namespace="http://tempuri.org/", Order=0)]
        public IMedico.localhostConsulta.pacienteTriagemResponseBody Body;
        
        public pacienteTriagemResponse() {
        }
        
        public pacienteTriagemResponse(IMedico.localhostConsulta.pacienteTriagemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class pacienteTriagemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IMedico.localhostConsulta.Consulta[] pacienteTriagemResult;
        
        public pacienteTriagemResponseBody() {
        }
        
        public pacienteTriagemResponseBody(IMedico.localhostConsulta.Consulta[] pacienteTriagemResult) {
            this.pacienteTriagemResult = pacienteTriagemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setMedicoConsultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMedicoConsulta", Namespace="http://tempuri.org/", Order=0)]
        public IMedico.localhostConsulta.setMedicoConsultaRequestBody Body;
        
        public setMedicoConsultaRequest() {
        }
        
        public setMedicoConsultaRequest(IMedico.localhostConsulta.setMedicoConsultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class setMedicoConsultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IMedico.localhostConsulta.Consulta c;
        
        public setMedicoConsultaRequestBody() {
        }
        
        public setMedicoConsultaRequestBody(IMedico.localhostConsulta.Consulta c) {
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setMedicoConsultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMedicoConsultaResponse", Namespace="http://tempuri.org/", Order=0)]
        public IMedico.localhostConsulta.setMedicoConsultaResponseBody Body;
        
        public setMedicoConsultaResponse() {
        }
        
        public setMedicoConsultaResponse(IMedico.localhostConsulta.setMedicoConsultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setMedicoConsultaResponseBody {
        
        public setMedicoConsultaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class finalizarConsultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="finalizarConsulta", Namespace="http://tempuri.org/", Order=0)]
        public IMedico.localhostConsulta.finalizarConsultaRequestBody Body;
        
        public finalizarConsultaRequest() {
        }
        
        public finalizarConsultaRequest(IMedico.localhostConsulta.finalizarConsultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class finalizarConsultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IMedico.localhostConsulta.Consulta c;
        
        public finalizarConsultaRequestBody() {
        }
        
        public finalizarConsultaRequestBody(IMedico.localhostConsulta.Consulta c) {
            this.c = c;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class finalizarConsultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="finalizarConsultaResponse", Namespace="http://tempuri.org/", Order=0)]
        public IMedico.localhostConsulta.finalizarConsultaResponseBody Body;
        
        public finalizarConsultaResponse() {
        }
        
        public finalizarConsultaResponse(IMedico.localhostConsulta.finalizarConsultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class finalizarConsultaResponseBody {
        
        public finalizarConsultaResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceConsultaSoapChannel : IMedico.localhostConsulta.ServiceConsultaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceConsultaSoapClient : System.ServiceModel.ClientBase<IMedico.localhostConsulta.ServiceConsultaSoap>, IMedico.localhostConsulta.ServiceConsultaSoap {
        
        public ServiceConsultaSoapClient() {
        }
        
        public ServiceConsultaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceConsultaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceConsultaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceConsultaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMedico.localhostConsulta.CadastrarConsultaResponse IMedico.localhostConsulta.ServiceConsultaSoap.CadastrarConsulta(IMedico.localhostConsulta.CadastrarConsultaRequest request) {
            return base.Channel.CadastrarConsulta(request);
        }
        
        public void CadastrarConsulta(IMedico.localhostConsulta.Consulta c) {
            IMedico.localhostConsulta.CadastrarConsultaRequest inValue = new IMedico.localhostConsulta.CadastrarConsultaRequest();
            inValue.Body = new IMedico.localhostConsulta.CadastrarConsultaRequestBody();
            inValue.Body.c = c;
            IMedico.localhostConsulta.CadastrarConsultaResponse retVal = ((IMedico.localhostConsulta.ServiceConsultaSoap)(this)).CadastrarConsulta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMedico.localhostConsulta.listarConsultaResponse IMedico.localhostConsulta.ServiceConsultaSoap.listarConsulta(IMedico.localhostConsulta.listarConsultaRequest request) {
            return base.Channel.listarConsulta(request);
        }
        
        public IMedico.localhostConsulta.Consulta[] listarConsulta() {
            IMedico.localhostConsulta.listarConsultaRequest inValue = new IMedico.localhostConsulta.listarConsultaRequest();
            inValue.Body = new IMedico.localhostConsulta.listarConsultaRequestBody();
            IMedico.localhostConsulta.listarConsultaResponse retVal = ((IMedico.localhostConsulta.ServiceConsultaSoap)(this)).listarConsulta(inValue);
            return retVal.Body.listarConsultaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMedico.localhostConsulta.pacienteTriagemResponse IMedico.localhostConsulta.ServiceConsultaSoap.pacienteTriagem(IMedico.localhostConsulta.pacienteTriagemRequest request) {
            return base.Channel.pacienteTriagem(request);
        }
        
        public IMedico.localhostConsulta.Consulta[] pacienteTriagem(IMedico.localhostConsulta.Consulta c) {
            IMedico.localhostConsulta.pacienteTriagemRequest inValue = new IMedico.localhostConsulta.pacienteTriagemRequest();
            inValue.Body = new IMedico.localhostConsulta.pacienteTriagemRequestBody();
            inValue.Body.c = c;
            IMedico.localhostConsulta.pacienteTriagemResponse retVal = ((IMedico.localhostConsulta.ServiceConsultaSoap)(this)).pacienteTriagem(inValue);
            return retVal.Body.pacienteTriagemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMedico.localhostConsulta.setMedicoConsultaResponse IMedico.localhostConsulta.ServiceConsultaSoap.setMedicoConsulta(IMedico.localhostConsulta.setMedicoConsultaRequest request) {
            return base.Channel.setMedicoConsulta(request);
        }
        
        public void setMedicoConsulta(IMedico.localhostConsulta.Consulta c) {
            IMedico.localhostConsulta.setMedicoConsultaRequest inValue = new IMedico.localhostConsulta.setMedicoConsultaRequest();
            inValue.Body = new IMedico.localhostConsulta.setMedicoConsultaRequestBody();
            inValue.Body.c = c;
            IMedico.localhostConsulta.setMedicoConsultaResponse retVal = ((IMedico.localhostConsulta.ServiceConsultaSoap)(this)).setMedicoConsulta(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IMedico.localhostConsulta.finalizarConsultaResponse IMedico.localhostConsulta.ServiceConsultaSoap.finalizarConsulta(IMedico.localhostConsulta.finalizarConsultaRequest request) {
            return base.Channel.finalizarConsulta(request);
        }
        
        public void finalizarConsulta(IMedico.localhostConsulta.Consulta c) {
            IMedico.localhostConsulta.finalizarConsultaRequest inValue = new IMedico.localhostConsulta.finalizarConsultaRequest();
            inValue.Body = new IMedico.localhostConsulta.finalizarConsultaRequestBody();
            inValue.Body.c = c;
            IMedico.localhostConsulta.finalizarConsultaResponse retVal = ((IMedico.localhostConsulta.ServiceConsultaSoap)(this)).finalizarConsulta(inValue);
        }
    }
}
