//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace IMedico.localhostReceita {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicoReceitaSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pessoa))]
    public partial class ServicoReceita : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CadastrarReceitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarReceitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarMedicamentosReceitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarMedicamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarReceitaConsultaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicoReceita() {
            this.Url = global::IMedico.Properties.Settings.Default.IMedico_localhostReceita_ServicoReceita;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CadastrarReceitaCompletedEventHandler CadastrarReceitaCompleted;
        
        /// <remarks/>
        public event BuscarReceitaCompletedEventHandler BuscarReceitaCompleted;
        
        /// <remarks/>
        public event listarMedicamentosReceitaCompletedEventHandler listarMedicamentosReceitaCompleted;
        
        /// <remarks/>
        public event ListarMedicamentoCompletedEventHandler ListarMedicamentoCompleted;
        
        /// <remarks/>
        public event registrarReceitaConsultaCompletedEventHandler registrarReceitaConsultaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastrarReceita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CadastrarReceita(Receita r) {
            object[] results = this.Invoke("CadastrarReceita", new object[] {
                        r});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarReceitaAsync(Receita r) {
            this.CadastrarReceitaAsync(r, null);
        }
        
        /// <remarks/>
        public void CadastrarReceitaAsync(Receita r, object userState) {
            if ((this.CadastrarReceitaOperationCompleted == null)) {
                this.CadastrarReceitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarReceitaOperationCompleted);
            }
            this.InvokeAsync("CadastrarReceita", new object[] {
                        r}, this.CadastrarReceitaOperationCompleted, userState);
        }
        
        private void OnCadastrarReceitaOperationCompleted(object arg) {
            if ((this.CadastrarReceitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarReceitaCompleted(this, new CadastrarReceitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarReceita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Receita[] BuscarReceita(Receita filtro) {
            object[] results = this.Invoke("BuscarReceita", new object[] {
                        filtro});
            return ((Receita[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarReceitaAsync(Receita filtro) {
            this.BuscarReceitaAsync(filtro, null);
        }
        
        /// <remarks/>
        public void BuscarReceitaAsync(Receita filtro, object userState) {
            if ((this.BuscarReceitaOperationCompleted == null)) {
                this.BuscarReceitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarReceitaOperationCompleted);
            }
            this.InvokeAsync("BuscarReceita", new object[] {
                        filtro}, this.BuscarReceitaOperationCompleted, userState);
        }
        
        private void OnBuscarReceitaOperationCompleted(object arg) {
            if ((this.BuscarReceitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarReceitaCompleted(this, new BuscarReceitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarMedicamentosReceita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceitaMedicamento[] listarMedicamentosReceita(ReceitaMedicamento filtro) {
            object[] results = this.Invoke("listarMedicamentosReceita", new object[] {
                        filtro});
            return ((ReceitaMedicamento[])(results[0]));
        }
        
        /// <remarks/>
        public void listarMedicamentosReceitaAsync(ReceitaMedicamento filtro) {
            this.listarMedicamentosReceitaAsync(filtro, null);
        }
        
        /// <remarks/>
        public void listarMedicamentosReceitaAsync(ReceitaMedicamento filtro, object userState) {
            if ((this.listarMedicamentosReceitaOperationCompleted == null)) {
                this.listarMedicamentosReceitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarMedicamentosReceitaOperationCompleted);
            }
            this.InvokeAsync("listarMedicamentosReceita", new object[] {
                        filtro}, this.listarMedicamentosReceitaOperationCompleted, userState);
        }
        
        private void OnlistarMedicamentosReceitaOperationCompleted(object arg) {
            if ((this.listarMedicamentosReceitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarMedicamentosReceitaCompleted(this, new listarMedicamentosReceitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarMedicamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Medicamento[] ListarMedicamento(Medicamento filtro) {
            object[] results = this.Invoke("ListarMedicamento", new object[] {
                        filtro});
            return ((Medicamento[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarMedicamentoAsync(Medicamento filtro) {
            this.ListarMedicamentoAsync(filtro, null);
        }
        
        /// <remarks/>
        public void ListarMedicamentoAsync(Medicamento filtro, object userState) {
            if ((this.ListarMedicamentoOperationCompleted == null)) {
                this.ListarMedicamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarMedicamentoOperationCompleted);
            }
            this.InvokeAsync("ListarMedicamento", new object[] {
                        filtro}, this.ListarMedicamentoOperationCompleted, userState);
        }
        
        private void OnListarMedicamentoOperationCompleted(object arg) {
            if ((this.ListarMedicamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarMedicamentoCompleted(this, new ListarMedicamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarReceitaConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void registrarReceitaConsulta(Consulta c) {
            this.Invoke("registrarReceitaConsulta", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void registrarReceitaConsultaAsync(Consulta c) {
            this.registrarReceitaConsultaAsync(c, null);
        }
        
        /// <remarks/>
        public void registrarReceitaConsultaAsync(Consulta c, object userState) {
            if ((this.registrarReceitaConsultaOperationCompleted == null)) {
                this.registrarReceitaConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarReceitaConsultaOperationCompleted);
            }
            this.InvokeAsync("registrarReceitaConsulta", new object[] {
                        c}, this.registrarReceitaConsultaOperationCompleted, userState);
        }
        
        private void OnregistrarReceitaConsultaOperationCompleted(object arg) {
            if ((this.registrarReceitaConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarReceitaConsultaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Receita {
        
        private int numeroField;
        
        private Paciente pacienteField;
        
        private Medico medicoField;
        
        private ReceitaMedicamento[] listaMedicamentosField;
        
        private string statusField;
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public Paciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
            }
        }
        
        /// <remarks/>
        public Medico Medico {
            get {
                return this.medicoField;
            }
            set {
                this.medicoField = value;
            }
        }
        
        /// <remarks/>
        public ReceitaMedicamento[] ListaMedicamentos {
            get {
                return this.listaMedicamentosField;
            }
            set {
                this.listaMedicamentosField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Paciente : Pessoa {
        
        private string nomePaiField;
        
        private string nomeMaeField;
        
        private string responsavelField;
        
        private string racaField;
        
        private string sexoField;
        
        private string cpfField;
        
        /// <remarks/>
        public string NomePai {
            get {
                return this.nomePaiField;
            }
            set {
                this.nomePaiField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public string Responsavel {
            get {
                return this.responsavelField;
            }
            set {
                this.responsavelField = value;
            }
        }
        
        /// <remarks/>
        public string Raca {
            get {
                return this.racaField;
            }
            set {
                this.racaField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Enfermeiro))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Medico))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Paciente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pessoa {
        
        private int idField;
        
        private string nomeField;
        
        private string telefoneField;
        
        private string rgField;
        
        private System.DateTime dataNascimentoField;
        
        private Endereco enderecoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Rg {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        public Endereco Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Endereco {
        
        private int idField;
        
        private string logradouroField;
        
        private int numeroField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string paisField;
        
        private string complementoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Diagnostico {
        
        private int idField;
        
        private System.DateTime dataField;
        
        private string informacoesField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Informacoes {
            get {
                return this.informacoesField;
            }
            set {
                this.informacoesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosVitais {
        
        private int idField;
        
        private System.DateTime dataField;
        
        private string pressaoField;
        
        private string pulsoField;
        
        private string temperaturaField;
        
        private string respiracaoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Pressao {
            get {
                return this.pressaoField;
            }
            set {
                this.pressaoField = value;
            }
        }
        
        /// <remarks/>
        public string Pulso {
            get {
                return this.pulsoField;
            }
            set {
                this.pulsoField = value;
            }
        }
        
        /// <remarks/>
        public string Temperatura {
            get {
                return this.temperaturaField;
            }
            set {
                this.temperaturaField = value;
            }
        }
        
        /// <remarks/>
        public string Respiracao {
            get {
                return this.respiracaoField;
            }
            set {
                this.respiracaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Consulta {
        
        private int numeroProntuarioField;
        
        private Paciente pacienteField;
        
        private Medico medicoField;
        
        private Enfermeiro enfermeiroField;
        
        private DadosVitais dadosVitaisField;
        
        private Diagnostico diagnosticoField;
        
        private Receita receitaField;
        
        private System.DateTime dataConsultaField;
        
        private string observacoesField;
        
        private string situacaoField;
        
        /// <remarks/>
        public int NumeroProntuario {
            get {
                return this.numeroProntuarioField;
            }
            set {
                this.numeroProntuarioField = value;
            }
        }
        
        /// <remarks/>
        public Paciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
            }
        }
        
        /// <remarks/>
        public Medico Medico {
            get {
                return this.medicoField;
            }
            set {
                this.medicoField = value;
            }
        }
        
        /// <remarks/>
        public Enfermeiro Enfermeiro {
            get {
                return this.enfermeiroField;
            }
            set {
                this.enfermeiroField = value;
            }
        }
        
        /// <remarks/>
        public DadosVitais DadosVitais {
            get {
                return this.dadosVitaisField;
            }
            set {
                this.dadosVitaisField = value;
            }
        }
        
        /// <remarks/>
        public Diagnostico Diagnostico {
            get {
                return this.diagnosticoField;
            }
            set {
                this.diagnosticoField = value;
            }
        }
        
        /// <remarks/>
        public Receita Receita {
            get {
                return this.receitaField;
            }
            set {
                this.receitaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataConsulta {
            get {
                return this.dataConsultaField;
            }
            set {
                this.dataConsultaField = value;
            }
        }
        
        /// <remarks/>
        public string Observacoes {
            get {
                return this.observacoesField;
            }
            set {
                this.observacoesField = value;
            }
        }
        
        /// <remarks/>
        public string Situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Medico : Pessoa {
        
        private string crmField;
        
        private string especializacaoField;
        
        private string loginField;
        
        private string senhaField;
        
        /// <remarks/>
        public string Crm {
            get {
                return this.crmField;
            }
            set {
                this.crmField = value;
            }
        }
        
        /// <remarks/>
        public string Especializacao {
            get {
                return this.especializacaoField;
            }
            set {
                this.especializacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Enfermeiro : Pessoa {
        
        private int corenField;
        
        /// <remarks/>
        public int Coren {
            get {
                return this.corenField;
            }
            set {
                this.corenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Medicamento {
        
        private int codigoField;
        
        private string nomeGenericoField;
        
        private string nomeComercialField;
        
        private string composicaoField;
        
        private string contraIndicacoesField;
        
        private string dosagemField;
        
        private string indicacoesField;
        
        private string fabricanteField;
        
        private string tipoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeGenerico {
            get {
                return this.nomeGenericoField;
            }
            set {
                this.nomeGenericoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeComercial {
            get {
                return this.nomeComercialField;
            }
            set {
                this.nomeComercialField = value;
            }
        }
        
        /// <remarks/>
        public string Composicao {
            get {
                return this.composicaoField;
            }
            set {
                this.composicaoField = value;
            }
        }
        
        /// <remarks/>
        public string ContraIndicacoes {
            get {
                return this.contraIndicacoesField;
            }
            set {
                this.contraIndicacoesField = value;
            }
        }
        
        /// <remarks/>
        public string Dosagem {
            get {
                return this.dosagemField;
            }
            set {
                this.dosagemField = value;
            }
        }
        
        /// <remarks/>
        public string Indicacoes {
            get {
                return this.indicacoesField;
            }
            set {
                this.indicacoesField = value;
            }
        }
        
        /// <remarks/>
        public string Fabricante {
            get {
                return this.fabricanteField;
            }
            set {
                this.fabricanteField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceitaMedicamento {
        
        private Medicamento medicamentoField;
        
        private Receita receitaField;
        
        private string instrucoesField;
        
        private string quantidadeField;
        
        private string dosagemField;
        
        private string tempoTratamentoField;
        
        /// <remarks/>
        public Medicamento Medicamento {
            get {
                return this.medicamentoField;
            }
            set {
                this.medicamentoField = value;
            }
        }
        
        /// <remarks/>
        public Receita Receita {
            get {
                return this.receitaField;
            }
            set {
                this.receitaField = value;
            }
        }
        
        /// <remarks/>
        public string Instrucoes {
            get {
                return this.instrucoesField;
            }
            set {
                this.instrucoesField = value;
            }
        }
        
        /// <remarks/>
        public string Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Dosagem {
            get {
                return this.dosagemField;
            }
            set {
                this.dosagemField = value;
            }
        }
        
        /// <remarks/>
        public string TempoTratamento {
            get {
                return this.tempoTratamentoField;
            }
            set {
                this.tempoTratamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CadastrarReceitaCompletedEventHandler(object sender, CadastrarReceitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarReceitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarReceitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void BuscarReceitaCompletedEventHandler(object sender, BuscarReceitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarReceitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarReceitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Receita[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Receita[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void listarMedicamentosReceitaCompletedEventHandler(object sender, listarMedicamentosReceitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarMedicamentosReceitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarMedicamentosReceitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceitaMedicamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceitaMedicamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ListarMedicamentoCompletedEventHandler(object sender, ListarMedicamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarMedicamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarMedicamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Medicamento[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Medicamento[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void registrarReceitaConsultaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591