//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace ProjetoFinal.localhostIAdmin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceMedicoSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pessoa))]
    public partial class WebServiceMedico : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CadastrarMedicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarMedicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback excluirMedicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback filtroMedicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback editarMedicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaMedicoOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaEnderecoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceMedico() {
            this.Url = global::ProjetoFinal.Properties.Settings.Default.ProjetoFinal_localhostIAdmin_WebServiceMedico;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CadastrarMedicoCompletedEventHandler CadastrarMedicoCompleted;
        
        /// <remarks/>
        public event listarMedicoCompletedEventHandler listarMedicoCompleted;
        
        /// <remarks/>
        public event excluirMedicoCompletedEventHandler excluirMedicoCompleted;
        
        /// <remarks/>
        public event filtroMedicoCompletedEventHandler filtroMedicoCompleted;
        
        /// <remarks/>
        public event editarMedicoCompletedEventHandler editarMedicoCompleted;
        
        /// <remarks/>
        public event listaMedicoCompletedEventHandler listaMedicoCompleted;
        
        /// <remarks/>
        public event listaEnderecoCompletedEventHandler listaEnderecoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastrarMedico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarMedico(Medico m, Endereco e) {
            this.Invoke("CadastrarMedico", new object[] {
                        m,
                        e});
        }
        
        /// <remarks/>
        public void CadastrarMedicoAsync(Medico m, Endereco e) {
            this.CadastrarMedicoAsync(m, e, null);
        }
        
        /// <remarks/>
        public void CadastrarMedicoAsync(Medico m, Endereco e, object userState) {
            if ((this.CadastrarMedicoOperationCompleted == null)) {
                this.CadastrarMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarMedicoOperationCompleted);
            }
            this.InvokeAsync("CadastrarMedico", new object[] {
                        m,
                        e}, this.CadastrarMedicoOperationCompleted, userState);
        }
        
        private void OnCadastrarMedicoOperationCompleted(object arg) {
            if ((this.CadastrarMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarMedicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarMedico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Medico[] listarMedico() {
            object[] results = this.Invoke("listarMedico", new object[0]);
            return ((Medico[])(results[0]));
        }
        
        /// <remarks/>
        public void listarMedicoAsync() {
            this.listarMedicoAsync(null);
        }
        
        /// <remarks/>
        public void listarMedicoAsync(object userState) {
            if ((this.listarMedicoOperationCompleted == null)) {
                this.listarMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarMedicoOperationCompleted);
            }
            this.InvokeAsync("listarMedico", new object[0], this.listarMedicoOperationCompleted, userState);
        }
        
        private void OnlistarMedicoOperationCompleted(object arg) {
            if ((this.listarMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarMedicoCompleted(this, new listarMedicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/excluirMedico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void excluirMedico(Medico m) {
            this.Invoke("excluirMedico", new object[] {
                        m});
        }
        
        /// <remarks/>
        public void excluirMedicoAsync(Medico m) {
            this.excluirMedicoAsync(m, null);
        }
        
        /// <remarks/>
        public void excluirMedicoAsync(Medico m, object userState) {
            if ((this.excluirMedicoOperationCompleted == null)) {
                this.excluirMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexcluirMedicoOperationCompleted);
            }
            this.InvokeAsync("excluirMedico", new object[] {
                        m}, this.excluirMedicoOperationCompleted, userState);
        }
        
        private void OnexcluirMedicoOperationCompleted(object arg) {
            if ((this.excluirMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.excluirMedicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/filtroMedico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Medico[] filtroMedico(string crm, string rg, string nome) {
            object[] results = this.Invoke("filtroMedico", new object[] {
                        crm,
                        rg,
                        nome});
            return ((Medico[])(results[0]));
        }
        
        /// <remarks/>
        public void filtroMedicoAsync(string crm, string rg, string nome) {
            this.filtroMedicoAsync(crm, rg, nome, null);
        }
        
        /// <remarks/>
        public void filtroMedicoAsync(string crm, string rg, string nome, object userState) {
            if ((this.filtroMedicoOperationCompleted == null)) {
                this.filtroMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfiltroMedicoOperationCompleted);
            }
            this.InvokeAsync("filtroMedico", new object[] {
                        crm,
                        rg,
                        nome}, this.filtroMedicoOperationCompleted, userState);
        }
        
        private void OnfiltroMedicoOperationCompleted(object arg) {
            if ((this.filtroMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.filtroMedicoCompleted(this, new filtroMedicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/editarMedico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void editarMedico(Medico m, Endereco e) {
            this.Invoke("editarMedico", new object[] {
                        m,
                        e});
        }
        
        /// <remarks/>
        public void editarMedicoAsync(Medico m, Endereco e) {
            this.editarMedicoAsync(m, e, null);
        }
        
        /// <remarks/>
        public void editarMedicoAsync(Medico m, Endereco e, object userState) {
            if ((this.editarMedicoOperationCompleted == null)) {
                this.editarMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OneditarMedicoOperationCompleted);
            }
            this.InvokeAsync("editarMedico", new object[] {
                        m,
                        e}, this.editarMedicoOperationCompleted, userState);
        }
        
        private void OneditarMedicoOperationCompleted(object arg) {
            if ((this.editarMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.editarMedicoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaMedico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Medico[] listaMedico(int idMedico) {
            object[] results = this.Invoke("listaMedico", new object[] {
                        idMedico});
            return ((Medico[])(results[0]));
        }
        
        /// <remarks/>
        public void listaMedicoAsync(int idMedico) {
            this.listaMedicoAsync(idMedico, null);
        }
        
        /// <remarks/>
        public void listaMedicoAsync(int idMedico, object userState) {
            if ((this.listaMedicoOperationCompleted == null)) {
                this.listaMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaMedicoOperationCompleted);
            }
            this.InvokeAsync("listaMedico", new object[] {
                        idMedico}, this.listaMedicoOperationCompleted, userState);
        }
        
        private void OnlistaMedicoOperationCompleted(object arg) {
            if ((this.listaMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaMedicoCompleted(this, new listaMedicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listaEndereco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Endereco[] listaEndereco(int idEndereco) {
            object[] results = this.Invoke("listaEndereco", new object[] {
                        idEndereco});
            return ((Endereco[])(results[0]));
        }
        
        /// <remarks/>
        public void listaEnderecoAsync(int idEndereco) {
            this.listaEnderecoAsync(idEndereco, null);
        }
        
        /// <remarks/>
        public void listaEnderecoAsync(int idEndereco, object userState) {
            if ((this.listaEnderecoOperationCompleted == null)) {
                this.listaEnderecoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaEnderecoOperationCompleted);
            }
            this.InvokeAsync("listaEndereco", new object[] {
                        idEndereco}, this.listaEnderecoOperationCompleted, userState);
        }
        
        private void OnlistaEnderecoOperationCompleted(object arg) {
            if ((this.listaEnderecoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaEnderecoCompleted(this, new listaEnderecoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Medico : Pessoa {
        
        private string crmField;
        
        private string especializacaoField;
        
        private string loginField;
        
        private string senhaField;
        
        /// <remarks/>
        public string Crm {
            get {
                return this.crmField;
            }
            set {
                this.crmField = value;
            }
        }
        
        /// <remarks/>
        public string Especializacao {
            get {
                return this.especializacaoField;
            }
            set {
                this.especializacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Medico))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pessoa {
        
        private int idField;
        
        private string nomeField;
        
        private string telefoneField;
        
        private string rgField;
        
        private System.DateTime dataNascimentoField;
        
        private Endereco enderecoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Rg {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        public Endereco Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Endereco {
        
        private int idField;
        
        private string logradouroField;
        
        private int numeroField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string paisField;
        
        private string complementoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CadastrarMedicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void listarMedicoCompletedEventHandler(object sender, listarMedicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarMedicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarMedicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Medico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Medico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void excluirMedicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void filtroMedicoCompletedEventHandler(object sender, filtroMedicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class filtroMedicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal filtroMedicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Medico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Medico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void editarMedicoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void listaMedicoCompletedEventHandler(object sender, listaMedicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaMedicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaMedicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Medico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Medico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void listaEnderecoCompletedEventHandler(object sender, listaEnderecoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaEnderecoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaEnderecoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Endereco[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Endereco[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591