//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace IMedico.localhostConsulta {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceConsultaSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pessoa))]
    public partial class ServiceConsulta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CadastrarConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback pacienteTriagemOperationCompleted;
        
        private System.Threading.SendOrPostCallback setMedicoConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback registrarDiagnosticoOperationCompleted;
        
        private System.Threading.SendOrPostCallback finalizarConsultaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarHistoricoConsultasOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarMedicosListOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginMedicoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceConsulta() {
            this.Url = global::IMedico.Properties.Settings.Default.IMedico_localhostConsulta_ServiceConsulta;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CadastrarConsultaCompletedEventHandler CadastrarConsultaCompleted;
        
        /// <remarks/>
        public event pacienteTriagemCompletedEventHandler pacienteTriagemCompleted;
        
        /// <remarks/>
        public event setMedicoConsultaCompletedEventHandler setMedicoConsultaCompleted;
        
        /// <remarks/>
        public event registrarDiagnosticoCompletedEventHandler registrarDiagnosticoCompleted;
        
        /// <remarks/>
        public event finalizarConsultaCompletedEventHandler finalizarConsultaCompleted;
        
        /// <remarks/>
        public event listarHistoricoConsultasCompletedEventHandler listarHistoricoConsultasCompleted;
        
        /// <remarks/>
        public event listarMedicosListCompletedEventHandler listarMedicosListCompleted;
        
        /// <remarks/>
        public event loginMedicoCompletedEventHandler loginMedicoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastrarConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CadastrarConsulta(Consulta c) {
            this.Invoke("CadastrarConsulta", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void CadastrarConsultaAsync(Consulta c) {
            this.CadastrarConsultaAsync(c, null);
        }
        
        /// <remarks/>
        public void CadastrarConsultaAsync(Consulta c, object userState) {
            if ((this.CadastrarConsultaOperationCompleted == null)) {
                this.CadastrarConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarConsultaOperationCompleted);
            }
            this.InvokeAsync("CadastrarConsulta", new object[] {
                        c}, this.CadastrarConsultaOperationCompleted, userState);
        }
        
        private void OnCadastrarConsultaOperationCompleted(object arg) {
            if ((this.CadastrarConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarConsultaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/pacienteTriagem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Consulta[] pacienteTriagem(Consulta c) {
            object[] results = this.Invoke("pacienteTriagem", new object[] {
                        c});
            return ((Consulta[])(results[0]));
        }
        
        /// <remarks/>
        public void pacienteTriagemAsync(Consulta c) {
            this.pacienteTriagemAsync(c, null);
        }
        
        /// <remarks/>
        public void pacienteTriagemAsync(Consulta c, object userState) {
            if ((this.pacienteTriagemOperationCompleted == null)) {
                this.pacienteTriagemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpacienteTriagemOperationCompleted);
            }
            this.InvokeAsync("pacienteTriagem", new object[] {
                        c}, this.pacienteTriagemOperationCompleted, userState);
        }
        
        private void OnpacienteTriagemOperationCompleted(object arg) {
            if ((this.pacienteTriagemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pacienteTriagemCompleted(this, new pacienteTriagemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/setMedicoConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void setMedicoConsulta(Consulta c) {
            this.Invoke("setMedicoConsulta", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void setMedicoConsultaAsync(Consulta c) {
            this.setMedicoConsultaAsync(c, null);
        }
        
        /// <remarks/>
        public void setMedicoConsultaAsync(Consulta c, object userState) {
            if ((this.setMedicoConsultaOperationCompleted == null)) {
                this.setMedicoConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetMedicoConsultaOperationCompleted);
            }
            this.InvokeAsync("setMedicoConsulta", new object[] {
                        c}, this.setMedicoConsultaOperationCompleted, userState);
        }
        
        private void OnsetMedicoConsultaOperationCompleted(object arg) {
            if ((this.setMedicoConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setMedicoConsultaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/registrarDiagnostico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int registrarDiagnostico(Consulta c) {
            object[] results = this.Invoke("registrarDiagnostico", new object[] {
                        c});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void registrarDiagnosticoAsync(Consulta c) {
            this.registrarDiagnosticoAsync(c, null);
        }
        
        /// <remarks/>
        public void registrarDiagnosticoAsync(Consulta c, object userState) {
            if ((this.registrarDiagnosticoOperationCompleted == null)) {
                this.registrarDiagnosticoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistrarDiagnosticoOperationCompleted);
            }
            this.InvokeAsync("registrarDiagnostico", new object[] {
                        c}, this.registrarDiagnosticoOperationCompleted, userState);
        }
        
        private void OnregistrarDiagnosticoOperationCompleted(object arg) {
            if ((this.registrarDiagnosticoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registrarDiagnosticoCompleted(this, new registrarDiagnosticoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/finalizarConsulta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void finalizarConsulta(Consulta c) {
            this.Invoke("finalizarConsulta", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void finalizarConsultaAsync(Consulta c) {
            this.finalizarConsultaAsync(c, null);
        }
        
        /// <remarks/>
        public void finalizarConsultaAsync(Consulta c, object userState) {
            if ((this.finalizarConsultaOperationCompleted == null)) {
                this.finalizarConsultaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfinalizarConsultaOperationCompleted);
            }
            this.InvokeAsync("finalizarConsulta", new object[] {
                        c}, this.finalizarConsultaOperationCompleted, userState);
        }
        
        private void OnfinalizarConsultaOperationCompleted(object arg) {
            if ((this.finalizarConsultaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.finalizarConsultaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarHistoricoConsultas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Consulta[] listarHistoricoConsultas(Consulta c) {
            object[] results = this.Invoke("listarHistoricoConsultas", new object[] {
                        c});
            return ((Consulta[])(results[0]));
        }
        
        /// <remarks/>
        public void listarHistoricoConsultasAsync(Consulta c) {
            this.listarHistoricoConsultasAsync(c, null);
        }
        
        /// <remarks/>
        public void listarHistoricoConsultasAsync(Consulta c, object userState) {
            if ((this.listarHistoricoConsultasOperationCompleted == null)) {
                this.listarHistoricoConsultasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarHistoricoConsultasOperationCompleted);
            }
            this.InvokeAsync("listarHistoricoConsultas", new object[] {
                        c}, this.listarHistoricoConsultasOperationCompleted, userState);
        }
        
        private void OnlistarHistoricoConsultasOperationCompleted(object arg) {
            if ((this.listarHistoricoConsultasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarHistoricoConsultasCompleted(this, new listarHistoricoConsultasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/listarMedicosList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Medico[] listarMedicosList() {
            object[] results = this.Invoke("listarMedicosList", new object[0]);
            return ((Medico[])(results[0]));
        }
        
        /// <remarks/>
        public void listarMedicosListAsync() {
            this.listarMedicosListAsync(null);
        }
        
        /// <remarks/>
        public void listarMedicosListAsync(object userState) {
            if ((this.listarMedicosListOperationCompleted == null)) {
                this.listarMedicosListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarMedicosListOperationCompleted);
            }
            this.InvokeAsync("listarMedicosList", new object[0], this.listarMedicosListOperationCompleted, userState);
        }
        
        private void OnlistarMedicosListOperationCompleted(object arg) {
            if ((this.listarMedicosListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarMedicosListCompleted(this, new listarMedicosListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/loginMedico", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Medico loginMedico(Medico m) {
            object[] results = this.Invoke("loginMedico", new object[] {
                        m});
            return ((Medico)(results[0]));
        }
        
        /// <remarks/>
        public void loginMedicoAsync(Medico m) {
            this.loginMedicoAsync(m, null);
        }
        
        /// <remarks/>
        public void loginMedicoAsync(Medico m, object userState) {
            if ((this.loginMedicoOperationCompleted == null)) {
                this.loginMedicoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginMedicoOperationCompleted);
            }
            this.InvokeAsync("loginMedico", new object[] {
                        m}, this.loginMedicoOperationCompleted, userState);
        }
        
        private void OnloginMedicoOperationCompleted(object arg) {
            if ((this.loginMedicoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginMedicoCompleted(this, new loginMedicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Consulta {
        
        private int numeroProntuarioField;
        
        private Paciente pacienteField;
        
        private Medico medicoField;
        
        private Enfermeiro enfermeiroField;
        
        private DadosVitais dadosVitaisField;
        
        private Diagnostico diagnosticoField;
        
        private Receita receitaField;
        
        private System.DateTime dataConsultaField;
        
        private string observacoesField;
        
        private string situacaoField;
        
        /// <remarks/>
        public int NumeroProntuario {
            get {
                return this.numeroProntuarioField;
            }
            set {
                this.numeroProntuarioField = value;
            }
        }
        
        /// <remarks/>
        public Paciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
            }
        }
        
        /// <remarks/>
        public Medico Medico {
            get {
                return this.medicoField;
            }
            set {
                this.medicoField = value;
            }
        }
        
        /// <remarks/>
        public Enfermeiro Enfermeiro {
            get {
                return this.enfermeiroField;
            }
            set {
                this.enfermeiroField = value;
            }
        }
        
        /// <remarks/>
        public DadosVitais DadosVitais {
            get {
                return this.dadosVitaisField;
            }
            set {
                this.dadosVitaisField = value;
            }
        }
        
        /// <remarks/>
        public Diagnostico Diagnostico {
            get {
                return this.diagnosticoField;
            }
            set {
                this.diagnosticoField = value;
            }
        }
        
        /// <remarks/>
        public Receita Receita {
            get {
                return this.receitaField;
            }
            set {
                this.receitaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataConsulta {
            get {
                return this.dataConsultaField;
            }
            set {
                this.dataConsultaField = value;
            }
        }
        
        /// <remarks/>
        public string Observacoes {
            get {
                return this.observacoesField;
            }
            set {
                this.observacoesField = value;
            }
        }
        
        /// <remarks/>
        public string Situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Paciente : Pessoa {
        
        private string nomePaiField;
        
        private string nomeMaeField;
        
        private string responsavelField;
        
        private string racaField;
        
        private string sexoField;
        
        private string cpfField;
        
        /// <remarks/>
        public string NomePai {
            get {
                return this.nomePaiField;
            }
            set {
                this.nomePaiField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public string Responsavel {
            get {
                return this.responsavelField;
            }
            set {
                this.responsavelField = value;
            }
        }
        
        /// <remarks/>
        public string Raca {
            get {
                return this.racaField;
            }
            set {
                this.racaField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Medico))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Enfermeiro))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Paciente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pessoa {
        
        private int idField;
        
        private string nomeField;
        
        private string telefoneField;
        
        private string rgField;
        
        private System.DateTime dataNascimentoField;
        
        private Endereco enderecoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Rg {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        public Endereco Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Endereco {
        
        private int idField;
        
        private string logradouroField;
        
        private int numeroField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string ufField;
        
        private string paisField;
        
        private string complementoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Medicamento {
        
        private int codigoField;
        
        private string nomeGenericoField;
        
        private string nomeComercialField;
        
        private string composicaoField;
        
        private string contraIndicacoesField;
        
        private string dosagemField;
        
        private string indicacoesField;
        
        private string fabricanteField;
        
        private string tipoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeGenerico {
            get {
                return this.nomeGenericoField;
            }
            set {
                this.nomeGenericoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeComercial {
            get {
                return this.nomeComercialField;
            }
            set {
                this.nomeComercialField = value;
            }
        }
        
        /// <remarks/>
        public string Composicao {
            get {
                return this.composicaoField;
            }
            set {
                this.composicaoField = value;
            }
        }
        
        /// <remarks/>
        public string ContraIndicacoes {
            get {
                return this.contraIndicacoesField;
            }
            set {
                this.contraIndicacoesField = value;
            }
        }
        
        /// <remarks/>
        public string Dosagem {
            get {
                return this.dosagemField;
            }
            set {
                this.dosagemField = value;
            }
        }
        
        /// <remarks/>
        public string Indicacoes {
            get {
                return this.indicacoesField;
            }
            set {
                this.indicacoesField = value;
            }
        }
        
        /// <remarks/>
        public string Fabricante {
            get {
                return this.fabricanteField;
            }
            set {
                this.fabricanteField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceitaMedicamento {
        
        private Medicamento medicamentoField;
        
        private Receita receitaField;
        
        private string instrucoesField;
        
        private string quantidadeField;
        
        private string dosagemField;
        
        private string tempoTratamentoField;
        
        /// <remarks/>
        public Medicamento Medicamento {
            get {
                return this.medicamentoField;
            }
            set {
                this.medicamentoField = value;
            }
        }
        
        /// <remarks/>
        public Receita Receita {
            get {
                return this.receitaField;
            }
            set {
                this.receitaField = value;
            }
        }
        
        /// <remarks/>
        public string Instrucoes {
            get {
                return this.instrucoesField;
            }
            set {
                this.instrucoesField = value;
            }
        }
        
        /// <remarks/>
        public string Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Dosagem {
            get {
                return this.dosagemField;
            }
            set {
                this.dosagemField = value;
            }
        }
        
        /// <remarks/>
        public string TempoTratamento {
            get {
                return this.tempoTratamentoField;
            }
            set {
                this.tempoTratamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Receita {
        
        private int numeroField;
        
        private Paciente pacienteField;
        
        private Medico medicoField;
        
        private ReceitaMedicamento[] listaMedicamentosField;
        
        private string statusField;
        
        /// <remarks/>
        public int Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public Paciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
            }
        }
        
        /// <remarks/>
        public Medico Medico {
            get {
                return this.medicoField;
            }
            set {
                this.medicoField = value;
            }
        }
        
        /// <remarks/>
        public ReceitaMedicamento[] ListaMedicamentos {
            get {
                return this.listaMedicamentosField;
            }
            set {
                this.listaMedicamentosField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Medico : Pessoa {
        
        private string crmField;
        
        private string especializacaoField;
        
        private string loginField;
        
        private string senhaField;
        
        /// <remarks/>
        public string Crm {
            get {
                return this.crmField;
            }
            set {
                this.crmField = value;
            }
        }
        
        /// <remarks/>
        public string Especializacao {
            get {
                return this.especializacaoField;
            }
            set {
                this.especializacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Diagnostico {
        
        private int idField;
        
        private System.DateTime dataField;
        
        private string informacoesField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Informacoes {
            get {
                return this.informacoesField;
            }
            set {
                this.informacoesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosVitais {
        
        private int idField;
        
        private System.DateTime dataField;
        
        private string pressaoField;
        
        private string pulsoField;
        
        private string temperaturaField;
        
        private string respiracaoField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Pressao {
            get {
                return this.pressaoField;
            }
            set {
                this.pressaoField = value;
            }
        }
        
        /// <remarks/>
        public string Pulso {
            get {
                return this.pulsoField;
            }
            set {
                this.pulsoField = value;
            }
        }
        
        /// <remarks/>
        public string Temperatura {
            get {
                return this.temperaturaField;
            }
            set {
                this.temperaturaField = value;
            }
        }
        
        /// <remarks/>
        public string Respiracao {
            get {
                return this.respiracaoField;
            }
            set {
                this.respiracaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Enfermeiro : Pessoa {
        
        private int corenField;
        
        /// <remarks/>
        public int Coren {
            get {
                return this.corenField;
            }
            set {
                this.corenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void CadastrarConsultaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void pacienteTriagemCompletedEventHandler(object sender, pacienteTriagemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pacienteTriagemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pacienteTriagemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Consulta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Consulta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void setMedicoConsultaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void registrarDiagnosticoCompletedEventHandler(object sender, registrarDiagnosticoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registrarDiagnosticoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registrarDiagnosticoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void finalizarConsultaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void listarHistoricoConsultasCompletedEventHandler(object sender, listarHistoricoConsultasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarHistoricoConsultasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarHistoricoConsultasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Consulta[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Consulta[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void listarMedicosListCompletedEventHandler(object sender, listarMedicosListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarMedicosListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarMedicosListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Medico[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Medico[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void loginMedicoCompletedEventHandler(object sender, loginMedicoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginMedicoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginMedicoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Medico Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Medico)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591